### ISSUE TITLE
Future improved disclosure channels

### ISSUE THREAD

**Issue by grctest** [RUB-NDS/Gridcoin-Attacks#1]
Hey,

Just to let you know in the future that the most optimal effective disclosure route is to contact the admins/mods on slack/irc/telegram/discord rather than the main 'contact' email address which is controlled by a single (but not the only) dev.
  There are many trusted devs on Slack who would have paid serious attention to your concerns at the time, likewise I'd have loved to have discussed your research over the last year during the [gridcoin community hangouts](https://soundcloud.com/gridcoin-community-hangouts) and would have helped escalate your concerns.

I've raised an issue regarding a [lack of clear vulnerability disclosure instructions on the gridcoin website](https://github.com/grctest/Gridcoin-Site/issues/70), hopefully we can improve communication between external researchers and gridcoin's developers in the future, learning from this experience.

Thank you for the time you've spent on this valuable research, I hope that you consider joining the Gridcoin community in the future if even to just troll us over your research findings.

Best regards,
CM.

**Comment by Kaedo** [comment]
Noted for future work.
